a_atoms = ["N1", "C2", "N3", "C4", "C5", "C6", "N7", "C8", "N9"]
g_atoms = ["N1", "C2", "N3", "C4", "C5", "C6", "N7", "C8", "N9"]
u_atoms = ["N1", "C2", "N3", "C4", "C5", "C6"]
c_atoms = ["N1", "C2", "N3", "C4", "C5", "C6"]
psu_atoms = ["N1", "C2", "N3", "C4", "C5", "C6"]
da_atoms = ["N1", "C2", "N3", "C4", "C5", "C6", "N7", "C8", "N9"]
dg_atoms = ["N1", "C2", "N3", "C4", "C5", "C6", "N7", "C8", "N9"]
dc_atoms = ["N1", "C2", "N3", "C4", "C5", "C6"]
dt_atoms = ["N1", "C2", "N3", "C4", "C5", "C6"]
trp_atoms = ["CG", "CD1", "NE1", "CE2", "CD2", "CE3", "CZ3", "CZ2", "CH2"]
tyro_atoms = ["CG", "CD1", "CE1", "CZ", "CD2", "CE2"]
his_atoms = ["ND1", "CG", "CE1", "NE2", "CD2"]
phe_atoms = ["CG", "CD1", "CD2", "CE1", "CE2", "CZ"]


residues = {
    "A": a_atoms,
    "G": g_atoms,
    "U": u_atoms,
    "C": c_atoms,
    "PSU": psu_atoms,
    "DG": dg_atoms,
    "DA": da_atoms,
    "DC": dc_atoms,
    "DT": dt_atoms,
    "TYR": tyro_atoms,
    "TRP": trp_atoms,
    "HIS": his_atoms,
    "PHE": phe_atoms,
    "8AN": a_atoms,
    "1MA": a_atoms,
    "AMP": a_atoms,
    "MTA": a_atoms,
    "A2M": a_atoms,
    "N6G": a_atoms,
    "2IA": a_atoms,
    "0A": a_atoms,
    "DTP": a_atoms,
    "A7C": a_atoms,
    "A44/": a_atoms,
    "SAH": a_atoms,
    "APC": a_atoms,
    "2MA": a_atoms,
    "7AT": a_atoms,
    "45A": a_atoms,
    "ZAD": a_atoms,
    "MIA": a_atoms,
    "PPU": a_atoms,
    "1DP": a_atoms,
    "A6A": a_atoms,
    "12A": a_atoms,
    "4M2/": a_atoms,
    "EEM": a_atoms,
    "CVC": a_atoms,
    "RIA": a_atoms,
    "QSQ": a_atoms,
    "F7O": a_atoms,
    "6MA": a_atoms,
    "A23/": a_atoms,
    "XAR": a_atoms,
    "6MZ": a_atoms,
    "LCA": a_atoms,
    "6HA": a_atoms,
    "31M": a_atoms,
    "3DA": a_atoms,
    "ATP": a_atoms,
    "AF2/": a_atoms,
    "F3N": a_atoms,
    "F6U": a_atoms,
    "A7E": a_atoms,
    "6MD": a_atoms,
    "AT7/": a_atoms,
    "PU": a_atoms,
    "6IA": a_atoms,
    "T6A": a_atoms,
    "P5P": a_atoms,
    "MA6/": a_atoms,
    "31H": a_atoms,
    "2BA": a_atoms,
    "ADN": a_atoms,
    "2AD": a_atoms,
    "AVC": a_atoms,
    "5AA": a_atoms,
    "M7A": a_atoms,
    "4BW": a_atoms,
    "SAM": a_atoms,
    "APN": a_atoms,
    "E7X": a_atoms,
    "ADS": a_atoms,
    "DSH": a_atoms,
    "Y5P": u_atoms,
    "UR3/": u_atoms,
    "UMO": u_atoms,
    "H2U": u_atoms,
    "A6U": u_atoms,
    "5IU": u_atoms,
    "UFB": u_atoms,
    "IU": u_atoms,
    "P4U": u_atoms,
    "2MU": u_atoms,
    "U4M": u_atoms,
    "U36/": u_atoms,
    "UOA": u_atoms,
    "HYG": u_atoms,
    "U33/": u_atoms,
    "0U": u_atoms,
    "2AU": u_atoms,
    "4SU": u_atoms,
    "UFT": u_atoms,
    "UTP": u_atoms,
    "OMU": u_atoms,
    "DOL": u_atoms,
    "6FU": u_atoms,
    "J48/": u_atoms,
    "URU": u_atoms,
    "5FU": u_atoms,
    "RUS": u_atoms,
    "H2U20^A": u_atoms,
    "UZR": u_atoms,
    "0U1/": u_atoms,
    "5BU": u_atoms,
    "UOB": u_atoms,
    "SSU": u_atoms,
    "BRU": u_atoms,
    "SUR": u_atoms,
    "UMS": u_atoms,
    "I4U": u_atoms,
    "U5M": u_atoms,
    "US5/": u_atoms,
    "U23/": u_atoms,
    "T5S": u_atoms,
    "U5R": u_atoms,
    "ZBU": u_atoms,
    "2KH": u_atoms,
    "C2E": g_atoms,
    "P7G": g_atoms,
    "DGP": g_atoms,
    "GDO": g_atoms,
    "B8W": g_atoms,
    "XUG": g_atoms,
    "PGN": g_atoms,
    "5GP": g_atoms,
    "ZGU": g_atoms,
    "M2G": g_atoms,
    "F73/": g_atoms,
    "HPA": g_atoms,
    "MHG": g_atoms,
    "GT3/": g_atoms,
    "B8K": g_atoms,
    "LCG": g_atoms,
    "G2P": g_atoms,
    "GRB": g_atoms,
    "GUN": g_atoms,
    "Q61/": g_atoms,
    "OMG": g_atoms,
    "E6G": g_atoms,
    "GNG": g_atoms,
    "5CG": g_atoms,
    "2MG": g_atoms,
    "QUO": g_atoms,
    "I": g_atoms,
    "7MG": g_atoms,
    "GMP": g_atoms,
    "PRF": g_atoms,
    "GNP": g_atoms,
    "G48/": g_atoms,
    "1MG": g_atoms,
    "B9B": g_atoms,
    "XGR": g_atoms,
    "GMX": g_atoms,
    "G4P": g_atoms,
    "F7U": g_atoms,
    "PGP": g_atoms,
    "0G": g_atoms,
    "G46/": g_atoms,
    "GDP": g_atoms,
    "23G": g_atoms,
    "BGM": g_atoms,
    "GPN": g_atoms,
    "Q1V": g_atoms,
    "G7M": g_atoms,
    "6HG": g_atoms,
    "MTU": g_atoms,
    "TG": g_atoms,
    "BGH": g_atoms,
    "SDG": g_atoms,
    "G5J": g_atoms,
    "GTP": g_atoms,
    "F7X": g_atoms,
    "E7G": g_atoms,
    "G47/": g_atoms,
    "2SG": g_atoms,
    "GF2/": g_atoms,
    "A6G": g_atoms,
    "1SC": c_atoms,
    "BLS": c_atoms,
    "5CF": c_atoms,
    "CTP": c_atoms,
    "AG9/": c_atoms,
    "1CC": c_atoms,
    "A6C": c_atoms,
    "N5M": c_atoms,
    "E3C": c_atoms,
    "S4C": c_atoms,
    "ZCY": c_atoms,
    "CFL": c_atoms,
    "CCC": c_atoms,
    "6HC": c_atoms,
    "OMC": c_atoms,
    "B9H": c_atoms,
    "O2C": c_atoms,
    "CFZ": c_atoms,
    "6FC": c_atoms,
    "B8Q": c_atoms,
    "5HM": c_atoms,
    "XCR": c_atoms,
    "DCZ": c_atoms,
    "C43/": c_atoms,
    "F6X": c_atoms,
    "CBV": c_atoms,
    "B8T": c_atoms,
    "QSK": c_atoms,
    "NCU": c_atoms,
    "LCC": c_atoms,
    "A5M": c_atoms,
    "5MC": c_atoms,
    "F7R": c_atoms,
    "LHH": c_atoms,
    "CBR": c_atoms,
    "N5C": c_atoms,
    "CPN": c_atoms,
    "M5M": c_atoms,
    "LV2/": c_atoms,
    "CSL": c_atoms,
    "0C": c_atoms,
    "JMH": c_atoms,
    "5CM": c_atoms,
    "73W": c_atoms,
    "5IC": c_atoms,
    "RSP": c_atoms,
    "DCT": c_atoms,
    "RSQ": c_atoms,
    "DOC": c_atoms,
    "4AC": c_atoms,
    "4OC": c_atoms,
    "70U": u_atoms,
    "T2T": u_atoms,
    "2MU": u_atoms,
    "CM0/": u_atoms,
    "5MU": u_atoms,
    "US3/": u_atoms,
    "TM2/": u_atoms,
    "TPN": u_atoms,
    "ZTH": u_atoms,
    "2QB": u_atoms,
    "XTR": u_atoms,
    "75B": u_atoms,
    "6HT": u_atoms,
    "6F7/": u_atoms,
    "MNU": u_atoms,
    "U8U": u_atoms,
    "TLN": u_atoms,
    "NTT": u_atoms,
    "8RJ": u_atoms,
}

Modified_t = {
    "70U",
    "T2T",
    "2MU",
    "CM0/",
    "5MU",
    "US3/",
    "TM2/",
    "TPN",
    "ZTH",
    "2QB",
    "XTR",
    "75B",
    "6HT",
    "6F7/",
    "MNU",
    "U8U",
    "TLN",
    "NTT",
    "8RJ",
}

Modified_c = {
    "1SC",
    "BLS",
    "5CF",
    "CTP",
    "AG9/",
    "1CC",
    "A6C",
    "N5M",
    "E3C",
    "S4C",
    "ZCY",
    "CFL",
    "CCC",
    "6HC",
    "OMC",
    "B9H",
    "O2C",
    "CFZ",
    "6FC",
    "B8Q",
    "5HM",
    "XCR",
    "DCZ",
    "C43/",
    "F6X",
    "CBV",
    "B8T",
    "QSK",
    "NCU",
    "LCC",
    "A5M",
    "5MC",
    "F7R",
    "LHH",
    "CBR",
    "N5C",
    "CPN",
    "M5M",
    "LV2/",
    "CSL",
    "0C",
    "JMH",
    "5CM",
    "73W",
    "5IC",
    "RSP",
    "DCT",
    "RSQ",
    "DOC",
    "4AC",
    "4OC",
}

Modified_g = {
    "C2E",
    "P7G",
    "DGP",
    "GDO",
    "B8W",
    "XUG",
    "PGN",
    "5GP",
    "ZGU",
    "M2G",
    "F73/",
    "HPA",
    "MHG",
    "GT3/",
    "B8K",
    "LCG",
    "G2P",
    "GRB",
    "GUN",
    "Q61/",
    "OMG",
    "E6G",
    "GNG",
    "5CG",
    "2MG",
    "QUO",
    "7MG",
    "GMP",
    "PRF",
    "GNP",
    "G48/",
    "1MG",
    "B9B",
    "XGR",
    "GMX",
    "G4P",
    "F7U",
    "PGP",
    "0G",
    "G46/",
    "GDP",
    "23G",
    "BGM",
    "GPN",
    "Q1V",
    "G7M",
    "6HG",
    "MTU",
    "TG",
    "BGH",
    "SDG",
    "G5J",
    "GTP",
    "F7X",
    "E7G",
    "G47/",
    "2SG",
    "GF2/",
    "A6G",
}

Modified_u = {
    "Y5P",
    "UR3/",
    "UMO",
    "H2U",
    "A6U",
    "5IU",
    "UFB",
    "IU",
    "P4U",
    "2MU",
    "U4M",
    "U36/",
    "UOA",
    "HYG",
    "U33/",
    "0U",
    "2AU",
    "4SU",
    "UFT",
    "UTP",
    "OMU",
    "DOL",
    "6FU",
    "J48/",
    "URU",
    "5FU",
    "RUS",
    "H2U20^A",
    "UZR",
    "0U1/",
    "5BU",
    "UOB",
    "SSU",
    "BRU",
    "SUR",
    "UMS",
    "I4U",
    "U5M",
    "US5/",
    "U23/",
    "T5S",
    "U5R",
    "ZBU",
    "2KH",
}

Modified_a = {
    "0A",
    "12A",
    "1DP",
    "1MA",
    "2AD",
    "2BA",
    "2IA",
    "2MA",
    "31H",
    "31M",
    "3DA",
    "45A",
    "4BW",
    "4M2/",
    "5AA",
    "6HA",
    "6IA",
    "6MA",
    "6MD",
    "6MZ",
    "7AT",
    "8AN",
    "A23/",
    "A2M",
    "A44/",
    "A6A",
    "A7C",
    "A7E",
    "ADN",
    "ADS",
    "AF2/",
    "AMP",
    "APC",
    "APN",
    "AT7/",
    "ATP",
    "AVC",
    "CVC",
    "DSH",
    "DTP",
    "E7X",
    "EEM",
    "F3N",
    "F6U",
    "F7O",
    "LCA",
    "M7A",
    "MA6/",
    "MIA",
    "MTA",
    "N6G",
    "P5P",
    "PPU",
    "PU",
    "QSQ",
    "RIA",
    "SAH",
    "SAM",
    "T6A",
    "XAR",
    "ZAD",
}

all_ring_names = list(residues.keys())


cation_pi = {
    "ARG": ["NE", "CZ", "NH1", "NH2"],
    "LYS": ["CE", "NZ"],
    "ASN": ["CG", "ND1"],
    "GLN": ["CD", "NE2"],
    "HIS": ["ND1", "NE2"],
}

sulfur_pi = {"CYS": ["SG"], "MET": ["SD"]}

anion_pi = {
    "GLU": ["OE1", "OE2"],
    "ASP": ["OD1", "OD2"],
    "A": ["OP1", "OP2", "PO1", "PO2"],
    "U": ["OP1", "OP2", "PO1", "PO2"],
    "G": ["OP1", "OP2", "PO1", "PO2"],
    "C": ["OP1", "OP2", "PO1", "PO2"],
    "PSU": ["OP1", "OP2", "PO1", "PO2"],
    "DA": ["OP1", "OP2", "PO1", "PO2"],
    "DT": ["OP1", "OP2", "PO1", "PO2"],
    "DG": ["OP1", "OP2", "PO1", "PO2"],
    "DC": ["OP1", "OP2", "PO1", "PO2"],
}

lone_pair_pi = {
    "A": ["O4'", "O2'", "O3'", "O5'"],
    "U": ["O2", "O4", "O4'", "O2'", "O3'", "O5'"],
    "G": ["O6", "N7", "O4'", "O2'", "O3'", "O5'"],
    "C": ["O2", "O4'", "O2'", "O3'", "O5'"],
    "PSU": ["O2", "O4", "O4'", "O2'", "O3'", "O5'"],
    "DA": ["O4'", "O2'", "O3'", "O5'"],
    "DT": ["O2", "O4", "O4'", "O2'", "O3'", "O5'"],
    "DG": ["O6", "N7", "O4'", "O2'", "O3'", "O5'"],
    "DC": ["O2", "O4'", "O2'", "O3'", "O5'"],
    "ALA": ["O"],
    "ASX": ["O"],
    "CYS": ["O"],
    "ASP": ["O"],
    "GLU": ["O"],
    "PHE": ["O"],
    "GLY": ["O"],
    "HIS": ["O"],
    "ILE": ["O"],
    "LYS": ["O"],
    "LEU": ["O"],
    "MET": ["O", "S"],
    "ASN": ["O", "OD1"],
    "PRO": ["O"],
    "GLN": ["O", "OE1"],
    "ARG": ["O"],
    "SER": ["O"],
    "THR": ["O"],
    "SEC": ["O"],
    "VAL": ["O"],
    "TRP": ["O"],
    "XAA": ["O"],
    "TYR": ["O"],
    "GLX": ["O"],
}

halogen_pi = {"BR": ["BR"], "CL": ["CL"], "F": ["F"], "I": ["I"]}


axis_definition_dictionary = {
    "A": [["N1", "C2"], "C6", 9],
    "G": [["N1", "C2"], "C6", 9],
    "U": [["N3"], "C4", 6],
    "C": [["N3"], "C4", 6],
    "PSU": [["N3"], "C2", 6],
    "DG": [["N1", "C2"], "C6", 9],
    "DA": [["N1", "C2"], "C6", 9],
    "DC": [["N3"], "C4", 6],
    "DT": [["N3"], "C4", 6],
    "TYR": [["CD1", "CE1"], "CZ", 6],
    "TRP": [["CZ3", "CH2"], "CZ2", 9],
    "HIS": [["CE1", "NE2"], "ND1", 5],
    "PHE": [["CD1", "CE1"], "CZ", 6],
}

THRESHOLDS = {6: [2.25, 2.25], 5: [1.57, 1.57], 9: [6.25, 2.25]}

AMINO_ACIDS = [
    "ALA",
    "ASX",
    "CYS",
    "ASP",
    "GLU",
    "PHE",
    "GLY",
    "HIS",
    "ILE",
    "LYS",
    "LEU",
    "MET",
    "ASN",
    "PRO",
    "GLN",
    "ARG",
    "SER",
    "THR",
    "SEC",
    "VAL",
    "TRP",
    "XAA",
    "TYR",
    "GLX",
]

HALOGENS = {"F": [], "CL": [], "BR": [], "I": []}

RADII = {
    "O": 1.52,
    "F": 1.47,
    "CL": 1.75,
    "BR": 1.85,
    "I": 1.98,
    "N": 1.55,
    "S": 1.80,
    "P": 1.80,
    "C": 1.70,
}


HALOGEN_ELECTRONEGATIVE = {
    "A": ["O4'", "O3'", "O5'", "OP1", "OP2"],
    "U": ["O2", "O4", "O4'", "O3'", "O5'", "OP1", "OP2"],
    "G": ["O6", "N7", "O4'", "O3'", "O5'", "OP1", "OP2"],
    "C": ["O2", "O4'", "O3'", "O5'", "OP1", "OP2"],
    "PSU": ["O2", "O4", "O4'", "O3'", "O5'", "OP1", "OP2"],
    "DA": ["O4'", "O3'", "O5'", "OP1", "OP2"],
    "DT": ["O2", "O4", "O4'", "O3'", "O5'", "OP1", "OP2"],
    "DG": ["O6", "N7", "O4'", "O3'", "O5'", "OP1", "OP2"],
    "DC": ["O2", "O4'", "O3'", "O5'", "OP1", "OP2"],
    "ALA": ["O"],
    "ASX": ["O"],
    "CYS": ["O"],
    "ASP": ["O", "OD1", "OD2"],
    "GLU": ["O", "OE1", "OE2"],
    "PHE": ["O"],
    "GLY": ["O"],
    "HIS": ["O"],
    "ILE": ["O"],
    "LYS": ["O"],
    "LEU": ["O"],
    "MET": ["O", "S"],
    "ASN": ["O", "OD1"],
    "PRO": ["O"],
    "GLN": ["O", "OE1"],
    "ARG": ["O"],
    "SER": ["O"],
    "THR": ["O"],
    "SEC": ["O"],
    "VAL": ["O"],
    "TRP": ["O"],
    "XAA": ["O"],
    "TYR": ["O"],
    "GLX": ["O"],
}


WATER_MEDIATED = {  # HETATM is O
    "A": ["O4'", "O3'", "O5'", "OP1", "OP2", "N7", "N6", "N1", "N3", "O2'"],
    "U": ["O2", "O4", "O4'", "O3'", "O5'", "OP1", "OP2", "N3", "O2'"],
    "G": ["O6", "N7", "O4'", "O3'", "O5'", "OP1", "OP2", "N7", "N1", "N3", "O2'"],
    "C": ["O2", "O4'", "O3'", "O5'", "OP1", "OP2", "N3", "N4", "O2'"],
    "PSU": ["O2", "O4", "O4'", "O3'", "O5'", "OP1", "OP2", "N1", "N3", "O2'"],
    "DA": ["O4'", "O3'", "O5'", "OP1", "OP2", "N7", "N6", "N1", "N3"],
    "DT": ["O2", "O4", "O4'", "O3'", "O5'", "OP1", "OP2", "N3"],
    "DG": ["O6", "N7", "O4'", "O3'", "O5'", "OP1", "OP2", "N7", "N1", "N3"],
    "DC": ["O2", "O4'", "O3'", "O5'", "OP1", "OP2", "N3", "N4"],
    "ALA": ["O", "OXT"],
    "ASX": ["O"],
    "CYS": ["O", "OXT", "SG"],
    "ASP": ["O", "OD1", "OD2", "OXT"],
    "GLU": ["O", "OE1", "OE2", "OXT"],
    "PHE": ["O", "OXT"],
    "GLY": ["O", "OXT"],
    "HIS": ["O", "OXT", "ND1", "CE1", "NE2", "CD2"],
    "ILE": ["O", "OXT"],
    "LYS": ["O", "OXT"],
    "LEU": ["O", "OXT"],
    "MET": ["O", "S", "OXT", "SD"],
    "ASN": ["O", "OD1", "OXT", "ND2"],
    "PRO": ["O", "OXT"],
    "GLN": ["O", "OE1", "OXT", "NE2"],
    "ARG": ["O", "OXT"],
    "SER": ["O", "OXT", "OG"],
    "THR": ["O", "OXT", "OG1"],
    "SEC": ["O"],
    "VAL": ["O", "OXT"],
    "TRP": ["O", "OXT"],
    "XAA": ["O"],
    "TYR": ["O", "OXT", "OH"],
    "GLX": ["O"],
}


METAL_MEDIATED = {  # to be changed later
    "A": ["O4'", "O3'", "O5'", "OP1", "OP2", "N7", "N6", "N1", "N3", "O2'"],
    "U": ["O2", "O4", "O4'", "O3'", "O5'", "OP1", "OP2", "N3", "O2'"],
    "G": ["O6", "N7", "O4'", "O3'", "O5'", "OP1", "OP2", "N7", "N1", "N3", "O2'"],
    "C": ["O2", "O4'", "O3'", "O5'", "OP1", "OP2", "N3", "N4", "O2'"],
    "PSU": ["O2", "O4", "O4'", "O3'", "O5'", "OP1", "OP2", "N1", "N3", "O2'"],
    "DA": ["O4'", "O3'", "O5'", "OP1", "OP2", "N7", "N6", "N1", "N3"],
    "DT": ["O2", "O4", "O4'", "O3'", "O5'", "OP1", "OP2", "N3"],
    "DG": ["O6", "N7", "O4'", "O3'", "O5'", "OP1", "OP2", "N7", "N1", "N3"],
    "DC": ["O2", "O4'", "O3'", "O5'", "OP1", "OP2", "N3", "N4"],
    "ALA": ["O", "OXT"],
    "ASX": ["O"],
    "CYS": ["O", "OXT", "SG"],
    "ASP": ["O", "OD1", "OD2", "OXT"],
    "GLU": ["O", "OE1", "OE2", "OXT"],
    "PHE": ["O", "OXT"],
    "GLY": ["O", "OXT"],
    "HIS": ["O", "OXT", "ND1", "CE1", "NE2", "CD2", "NE1"],
    "ILE": ["O", "OXT"],
    "LYS": ["O", "OXT"],
    "LEU": ["O", "OXT"],
    "MET": ["O", "S", "OXT", "SD"],
    "ASN": ["O", "OD1", "OXT", "ND2"],
    "PRO": ["O", "OXT"],
    "GLN": ["O", "OE1", "OXT", "NE2"],
    "ARG": ["O", "OXT"],
    "SER": ["O", "OXT", "OG"],
    "THR": ["O", "OXT", "OG1"],
    "SEC": ["O"],
    "VAL": ["O", "OXT"],
    "TRP": ["O", "OXT"],
    "XAA": ["O"],
    "TYR": ["O", "OXT", "OH"],
    "GLX": ["O"],
}

"""Adding modifications to all the dictionaries"""
for mod in Modified_a:
    axis_definition_dictionary[mod] = axis_definition_dictionary["A"]
    anion_pi[mod] = anion_pi["A"]
    lone_pair_pi[mod] = lone_pair_pi["A"]
    HALOGEN_ELECTRONEGATIVE[mod] = HALOGEN_ELECTRONEGATIVE["A"]
    WATER_MEDIATED[mod] = WATER_MEDIATED["A"]
    METAL_MEDIATED[mod] = METAL_MEDIATED["A"]
for mod in Modified_g:
    axis_definition_dictionary[mod] = axis_definition_dictionary["G"]
    anion_pi[mod] = anion_pi["G"]
    anion_pi[mod] = anion_pi["G"]
    lone_pair_pi[mod] = lone_pair_pi["G"]
    HALOGEN_ELECTRONEGATIVE[mod] = HALOGEN_ELECTRONEGATIVE["G"]
    WATER_MEDIATED[mod] = WATER_MEDIATED["G"]
    METAL_MEDIATED[mod] = METAL_MEDIATED["G"]
for mod in Modified_c:
    axis_definition_dictionary[mod] = axis_definition_dictionary["C"]
    anion_pi[mod] = anion_pi["C"]
    anion_pi[mod] = anion_pi["C"]
    lone_pair_pi[mod] = lone_pair_pi["C"]
    HALOGEN_ELECTRONEGATIVE[mod] = HALOGEN_ELECTRONEGATIVE["C"]
    WATER_MEDIATED[mod] = WATER_MEDIATED["C"]
    METAL_MEDIATED[mod] = METAL_MEDIATED["C"]
for mod in Modified_u:
    axis_definition_dictionary[mod] = axis_definition_dictionary["U"]
    anion_pi[mod] = anion_pi["U"]
    anion_pi[mod] = anion_pi["U"]
    lone_pair_pi[mod] = lone_pair_pi["U"]
    HALOGEN_ELECTRONEGATIVE[mod] = HALOGEN_ELECTRONEGATIVE["U"]
    WATER_MEDIATED[mod] = WATER_MEDIATED["U"]
    METAL_MEDIATED[mod] = METAL_MEDIATED["U"]

# all will be found in HETATM
METALS = set(
    [
        "LI",
        "BE",
        "NA",
        "MG",
        "AL",
        "K",
        "CA",
        "SC",
        "TI",
        "V",
        "CR",
        "MN",
        "FE",
        "CO",
        "NI",
        "CU",
        "ZN",
        "GA",
        "RB",
        "SR",
        "Y",
        "ZR",
        "NB",
        "MO",
        "TC",
        "RU",
        "RH",
        "PD",
        "AG",
        "CD",
        "IN",
        "SN",
        "CS",
        "BA",
        "LA",
        "CE",
        "PR",
        "ND",
        "PM",
        "SM",
        "EU",
        "GD",
        "TB",
        "DY",
        "HO",
        "ER",
        "TM",
        "YB",
        "LU",
        "HF",
        "TA",
        "W",
        "RE",
        "OS",
        "IR",
        "PT",
        "AU",
        "HG",
        "TL",
        "PB",
        "BI",
        "PO",
        "FR",
        "RA",
        "AC",
        "TH",
        "PA",
        "U",
        "NP",
        "PU",
        "AM",
        "CM",
        "BK",
        "CF",
    ]
)

METAL_DISTANCES = {
    "AG": 3.0,
    "BI": 3.0,
    "RE": 3.0,
    "Y": 3.0,
    "DY": 3.0,
    "EU": 3.0,
    "HO": 3.0,
    "HF": 3.0,
    "PU": 3.0,
    "HG": 3.0,
    "ND": 3.0,
    "CS": 3.0,
    "PA": 3.0,
    "V": 3.0,
    "IR": 3.0,
    "LU": 3.0,
    "CD": 3.0,
    "RB": 3.0,
    "PR": 3.0,
    "GA": 3.0,
    "ER": 3.0,
    "MO": 3.0,
    "AC": 3.0,
    "CF": 3.0,
    "CU": 3.0,
    "CO": 3.0,
    "NB": 3.0,
    "PB": 3.0,
    "SR": 3.0,
    "ZN": 3.0,
    "TH": 3.0,
    "TA": 3.0,
    "LA": 3.0,
    "NP": 3.0,
    "GD": 3.0,
    "RH": 3.0,
    "MN": 3.0,
    "AU": 3.0,
    "RA": 3.0,
    "BK": 3.0,
    "NA": 3.0,
    "TC": 3.0,
    "PM": 3.0,
    "TL": 3.0,
    "LI": 3.0,
    "SM": 3.0,
    "W": 3.0,
    "MG": 3.0,
    "NI": 3.0,
    "TB": 3.0,
    "SC": 3.0,
    "FE": 3.0,
    "K": 3.0,
    "OS": 3.0,
    "TI": 3.0,
    "PD": 3.0,
    "TM": 3.0,
    "YB": 3.0,
    "PO": 3.0,
    "CR": 3.0,
    "ZR": 3.0,
    "IN": 3.0,
    "SN": 3.0,
    "CE": 3.0,
    "FR": 3.0,
    "AM": 3.0,
    "BA": 3.0,
    "AL": 3.0,
    "CA": 3.0,
    "RU": 3.0,
    "PT": 3.0,
    "BE": 3.0,
    "CM": 3.0,
    "U": 3.0,
}
